# Generated by Django 5.0.4 on 2024-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGoal', models.IntegerField(default=0, verbose_name='ID_Metas')),
                ('goalName', models.CharField(max_length=50, verbose_name='Meta')),
            ],
        ),
    ]
