# Generated by Django 5.2.3 on 2025-11-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Investigador')], default=2, verbose_name='Rol del Usuario'),
        ),
    ]
