# Generated by Django 5.0.4 on 2024-07-10 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='El formato de CURP no es válido', regex='^[A-Z]{4}[0-9]{6}[A-Z]{7}[0-9]{1}$')])),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-Z\\s]*$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El formato del apellido no es válido', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('career', models.CharField(max_length=50)),
            ],
        ),
    ]
