# Generated by Django 5.0.4 on 2024-07-10 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El formato del RFC no es válido', regex='^[A-Z]{4}\\d{6}[A-Z0-9]{3}$')])),
                ('companyName', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El formato del nombre de la compañía no es válido', regex='^[a-zA-Z0-9\\s\\.\\&\\-]+$')])),
                ('businessName', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El formato del business Name no es valido', regex='^[a-zA-Z0-9\\s\\.\\&\\-]+$')])),
                ('sector', models.CharField(choices=[('PB', 'Publico'), ('PV', 'Privado')], default='PB', max_length=2)),
                ('companyType', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El Tipo de la comañia no es valido', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\.\\&\\-]+$')])),
            ],
        ),
    ]
