# Generated by Django 5.2 on 2025-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rfc',
            field=models.CharField(max_length=13),
        ),
    ]
