# Generated by Django 5.0.4 on 2024-07-10 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-Z\\s]*$')], verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El formato del apellido no es válido', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Apellido')),
                ('controlN', models.CharField(default='---------', max_length=9, verbose_name='Numero de control')),
                ('semester', models.CharField(default='1er semestre', max_length=50, verbose_name='Semestre')),
                ('career', models.CharField(default='Sistemas computacionales', max_length=255, verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
