# Generated by Django 5.0.4 on 2024-07-10 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfcCall', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El formato del RFC no es válido', regex='^[A-ZÑ&]{3,4}\\d{6}(?:[A-Z\\d]{2}[A\\d])?$')])),
                ('callN', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El formato del nombre de la convocatoria no es válido', regex='^[a-zA-Z0-9\\s\\.\\&\\-]+$')])),
                ('callBegin', models.DateField()),
                ('callEnd', models.DateField()),
                ('callDesc', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='El formato de la descripción no es válido', regex='^[\\w\\s\\.\\,\\&\\-]{0,200}$')])),
            ],
        ),
    ]
