# Generated by Django 5.0.4 on 2024-06-17 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lgac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLine', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El formato del nombre de la compañía no es válido', regex='^[a-zA-Z0-9\\s\\.\\&\\-]+$')])),
                ('career', models.CharField(max_length=252, validators=[django.core.validators.RegexValidator(message='El formato del nombre de la carrera de ingeniería no es válido', regex='^Ingeniería\\s[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\.\\&\\-]+$')])),
                ('instituto', models.CharField(choices=[('TecNM', 'Tecnologico de Mexico'), ('PRODEP-CA', 'PRODEP')], default='TecNM', max_length=30)),
            ],
        ),
    ]
