# Generated by Django 5.0.4 on 2024-07-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.URLField(verbose_name='URL documentos')),
                ('informe', models.URLField(verbose_name='URL documentos')),
                ('registro', models.URLField(verbose_name='URL documentos')),
                ('carta', models.URLField(verbose_name='URL documentos')),
            ],
        ),
    ]
