# Generated by Django 5.0.4 on 2024-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_file',
            name='carta',
            field=models.URLField(verbose_name='URL carta de terceros'),
        ),
        migrations.AlterField(
            model_name='doc_file',
            name='informe',
            field=models.URLField(verbose_name='URL informe'),
        ),
        migrations.AlterField(
            model_name='doc_file',
            name='protocolo',
            field=models.URLField(verbose_name='URL protocolo'),
        ),
        migrations.AlterField(
            model_name='doc_file',
            name='registro',
            field=models.URLField(verbose_name='URL registro'),
        ),
    ]
