# Generated by Django 5.0.4 on 2024-07-10 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0001_initial'),
        ('company', '0001_initial'),
        ('lgac', '0001_initial'),
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internCode', models.CharField(max_length=15, verbose_name='Calve interna')),
                ('projectName', models.CharField(max_length=254, verbose_name='Nombre del proyecto')),
                ('objetives', models.TextField(verbose_name='Objetivos')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('invArea', models.CharField(choices=[('ED', 'EDUCACION'), ('AH', 'ARTES Y HUMANIDADES'), ('SC', 'CIENCIAS SOCIALES ADMINISTRACION Y DERECHO'), ('AN', 'ADMINISTRACION Y NEGOCIOS'), ('CN', 'CIENCIAS NATURALES EXACTAS Y DE LA COMPUTACION'), ('TICs', 'TECNOLOGÍA DE LA INFORMACIÓN Y LA COMUNICACIÓN'), ('IMC', 'INGENIERIA MANOFACTURA Y CONSTRUCCIÓN'), ('AV', 'AGRONOMIA Y VETERINARIA'), ('SD', 'SALUD'), ('SV', 'SERVICIOS')], default='CN', max_length=50)),
                ('dateBegin', models.DateField(verbose_name='Fecha de inicio')),
                ('dateEnd', models.DateField(verbose_name='Fecha de inicio')),
                ('financing', models.BooleanField(verbose_name='Financiamiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto')),
                ('linked', models.BooleanField(verbose_name='Vinculado')),
                ('projectcol', models.CharField(max_length=50)),
                ('lgac_Linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgac.lgac')),
                ('projectLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.researcher')),
                ('rfcCall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.call')),
                ('rfcCom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
