# Generated by Django 5.2 on 2025-05-21 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000.0)], verbose_name='Monto'),
        ),
    ]
