# Generated by Django 5.2 on 2025-05-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='internCode',
            field=models.CharField(max_length=15, verbose_name='Clave interna'),
        ),
    ]
