# Generated by Django 5.2 on 2025-05-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_interncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='internCode',
            field=models.CharField(blank=True, editable=False, max_length=15, verbose_name='Clave interna'),
        ),
    ]
