# Generated by Django 5.2 on 2025-05-21 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_interncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1000.0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dateEnd',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
    ]
