# Generated by Django 5.2 on 2025-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_amount_alter_project_dateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='objetives',
            field=models.TextField(max_length=1000, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=1000, verbose_name='Resumen'),
        ),
    ]
